config/routes.rb
Rails.application.routes.draw do
  resources :hospital_profiles
  resources :patient_tests
  devise_for :users, :controllers => { registrations: 'registrations'}

  root :to => 'home#index'
  resources :roles
  get '/role/:id/abilities'     => 'roles#change_abilities',  as: :change_role_abilities
  post '/role/:id/update-abilities' => 'roles#update_abilities',  as: :update_role_abilities
  get '/patients' => 'patients#index'
  get '/manage-patient/:id' => 'patients#manage_patient', as: :manage_patient
  patch '/update-patient/:id' => 'patients#update_patient', as: :update_patient
  get '/manage-test/:id' => 'patients#manage_test', as: :manage_test
  post '/update-test/:id' => 'patients#update_test', as: :update_test
  delete '/manage-test/:id/:pid' => 'patients#destroy_test', as: :destroy_test
  get '/manage-profile/:id' => 'patients#show', as: :profile
  get '/edit-profile/:id' => 'patients#edit', as: :edit_profile
  put '/update-profile/:id' => 'patients#update_profile', as: :update_profile

end

app/views/layouts/parts/_header.html.erb
<header>
	<% if user_signed_in? %>
		<%= link_to destroy_user_session_path, method: :delete, class: 'pull-right btn btn-danger logout' do %>
			<i class="fa fa-sign-out fa-lg"></i>
			Logout
		<% end %>
	<% end %>
</header>

app/views/layouts/parts/_side_nav.html.erb
<div class="col-sm-3 col-md-2 sidebar">
	<ul class="nav nav-sidebar">
		<li><%= active_link_to 'Hospital Profile', hospital_profile_path(HospitalProfile.last) %></li>
		<li><%= active_link_to 'Manage Roles', roles_path %></li>
		<% if current_user.has_role?('hospital') %>
			<li><%= active_link_to 'Manage Patients', patients_path %></li>
		<% end %>
		<% if !current_user.has_role?('hospital') %>
			<li><%= active_link_to 'Manage Profile', profile_path(current_user) %></li>
		<% end %>
	</ul>
</div>