config/routes.rb
Rails.application.routes.draw do
  resources :hospital_profiles
  resources :patient_tests
  devise_for :users, :controllers => { registrations: 'registrations'}

  root :to => 'home#index'
  resources :roles
  get '/role/:id/abilities'     => 'roles#change_abilities',  as: :change_role_abilities
  post '/role/:id/update-abilities' => 'roles#update_abilities',  as: :update_role_abilities
  get '/patients' => 'patients#index'
  get '/manage-patient/:id' => 'patients#manage_patient', as: :manage_patient
  patch '/update-patient/:id' => 'patients#update_patient', as: :update_patient
  get '/manage-test/:id' => 'patients#manage_test', as: :manage_test
  post '/update-test/:id' => 'patients#update_test', as: :update_test
  delete '/manage-test/:id/:pid' => 'patients#destroy_test', as: :destroy_test
  get '/manage-profile/:id' => 'patients#show', as: :profile
  get '/edit-profile/:id' => 'patients#edit', as: :edit_profile
  put '/update-profile/:id' => 'patients#update_profile', as: :update_profile

end

app/models/hospital_profile.rb
class HospitalProfile
	include Mongoid::Document
	
	field :name, type: String
	field :about, type: String
	field :location, type: String

	validates_presence_of :name, :about, :location
end

app/controllers/hospital_profiles_controller.rb
class HospitalProfilesController < ApplicationController
  before_action :set_hospital_profile, only: [:show, :edit, :update, :destroy]

  before_filter :load_permissions
  load_and_authorize_resource param_method: :hospital_profile_params
  # GET /hospital_profiles
  # GET /hospital_profiles.json
  def index
    @hospital_profiles = HospitalProfile.all
  end

  # GET /hospital_profiles/1
  # GET /hospital_profiles/1.json
  def show
  end

  # GET /hospital_profiles/new
  def new
    @hospital_profile = HospitalProfile.new
  end

  # GET /hospital_profiles/1/edit
  def edit
  end

  # POST /hospital_profiles
  # POST /hospital_profiles.json
  def create
    @hospital_profile = HospitalProfile.new(hospital_profile_params)

    respond_to do |format|
      if @hospital_profile.save
        format.html { redirect_to root_path, notice: 'Hospital profile was successfully created.' }
        format.json { render :show, status: :created, location: @hospital_profile }
      else
        format.html { render :new }
        format.json { render json: @hospital_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospital_profiles/1
  # PATCH/PUT /hospital_profiles/1.json
  def update
    respond_to do |format|
      if @hospital_profile.update(hospital_profile_params)
        format.html { redirect_to @hospital_profile, notice: 'Hospital profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital_profile }
      else
        format.html { render :edit }
        format.json { render json: @hospital_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospital_profiles/1
  # DELETE /hospital_profiles/1.json
  def destroy
    @hospital_profile.destroy
    respond_to do |format|
      format.html { redirect_to hospital_profiles_url, notice: 'Hospital profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def self.permission
    return 'HospitalProfile'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital_profile
      @hospital_profile = HospitalProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_profile_params
      params.require(:hospital_profile).permit(:name, :about, :location)
    end
end

app/helpers/hospital_profiles_helper.rb
module HospitalProfilesHelper
end

app/views/hospital_profiles/_form.html.erb
<div class="panel-layout">
	<div class="panel panel-default">
		<div class="panel-heading">Hospital Information</div>
		<div class="panel-body">
			<%= form_for(@hospital_profile) do |f| %>
				<div class="field">
					<%= f.label :name %><br>
					<%= f.text_field :name, class: 'form-control' %>
				</div>
				<div class="field">
					<%= f.label :about %><br>
					<%= f.text_area :about, class: 'form-control' %>
				</div>
				<div class="field">
					<%= f.label :location %><br>
					<%= f.text_field :location, class: 'form-control' %>
				</div>
				<div class="actions text-center">
					<%= f.submit class: 'btn btn-success' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/hospital_profiles/edit.html.erb
<%= render 'form' %>

app/views/hospital_profiles/index.html.erb
<div class="container">
	<h2></h2>
	<% if HospitalProfile.count == 0 %>
	<div class="registration">
		Please click <%= link_to 'Here', new_hospital_profile_path %> to register the hospital details
	</div>
	<% end %>
</div>

app/views/hospital_profiles/new.html.erb
<%= render 'form' %>

app/views/hospital_profiles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @hospital_profile.name %>
</p>
<p>
  <strong>About:</strong>
  <%= @hospital_profile.about %>
</p>
<p>
  <strong>Location:</strong>
  <%= @hospital_profile.location %>
</p>
<%= link_to 'Edit', edit_hospital_profile_path(@hospital_profile) %>