config/routes.rb
Rails.application.routes.draw do
  resources :hospital_profiles
  resources :patient_tests
  devise_for :users, :controllers => { registrations: 'registrations'}

  root :to => 'home#index'
  resources :roles
  get '/role/:id/abilities'     => 'roles#change_abilities',  as: :change_role_abilities
  post '/role/:id/update-abilities' => 'roles#update_abilities',  as: :update_role_abilities
  get '/patients' => 'patients#index'
  get '/manage-patient/:id' => 'patients#manage_patient', as: :manage_patient
  patch '/update-patient/:id' => 'patients#update_patient', as: :update_patient
  get '/manage-test/:id' => 'patients#manage_test', as: :manage_test
  post '/update-test/:id' => 'patients#update_test', as: :update_test
  delete '/manage-test/:id/:pid' => 'patients#destroy_test', as: :destroy_test
  get '/manage-profile/:id' => 'patients#show', as: :profile
  get '/edit-profile/:id' => 'patients#edit', as: :edit_profile
  put '/update-profile/:id' => 'patients#update_profile', as: :update_profile

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	
	before_filter :is_hospital?, :except => [:show, :edit, :update_profile]
	before_action :set_patient, only: [:manage_patient, :update_patient, :manage_test, :update_test, :destroy_test, :show, :edit, :update_profile]
	
	def index
		@users = User.where(:id.ne => current_user.id)
	end

	def show
	end

	def edit
	end

	def update_profile
		@patient.first_name = params[:user][:first_name]
		@patient.last_name = params[:user][:last_name]
		@patient.location = params[:user][:location]
		@patient.save
		redirect_to profile_path
		flash[:notice] = 'User updated successfully'
	end

	def manage_patient
	end

	def update_patient
		@patient.update(weight: params[:user][:weight], temperature: params[:user][:temperature])
		redirect_to manage_patient_path
		flash[:notice] = 'Patient measures updated successfully'
	end

	def manage_test
		@patient_test = PatientTest.new
		@patient_tests = @patient.patient_tests
	end

	def update_test
		@patient_test = @patient.patient_tests.new(patient_test_params)
		if @patient_test.save
			flash[:alert] = 'Patient condition recorded'
		end
		redirect_to manage_test_path(@patient)
	end

	def destroy_test
		@patient_test = PatientTest.find(params[:pid])
		@patient_test.destroy
		redirect_to manage_test_path(@patient)
		flash[:notice] = 'Test removed successfully'
	end	

	private

	def set_patient
		@patient = User.find(params[:id])
	end

	def patient_test_params
		params.require(:patient_test).permit(:name, :result)
	end

	def is_hospital?
		redirect_to root_path, flash: { notice: 'Access denied. You are not authorized to access the requested page. Only hospital management can access roles.' } and return unless current_user.has_role? :hospital
	end
end

app/views/patients/edit.html.erb
<div class="panel-layout">
	<div class="panel panel-default">
		<div class="panel-heading">Edit Account Information</div>
		<div class="panel-body">
			<%= form_for(@patient, url: update_profile_path(@patient), html: { method: :put }) do |f| %>
				<div class="field">
					<%= f.label :first_name %><br />
					<%= f.text_field :first_name, autofocus: true, class: 'form-control' %>
				</div>
				<div class="field">
					<%= f.label :last_name %><br />
					<%= f.text_field :last_name, autofocus: true, class: 'form-control' %>
				</div>
				<div class="field">
					<%= f.label :account_number %><br />
					<%= f.text_field :account_number, autofocus: true, readonly: true, class: 'form-control' %>
				</div>
				<div class='gmaps'>
					<div class='input-gmaps-autocomplete'>
						<%= f.text_field :location, id: 'gmaps-input-address', class: 'text-tab form-control', placeholder: 'address' %>
						<div class='gmaps-error'></div>
					</div>
					<div id='gmaps-canvas'></div>
				</div>
				<div class="actions text-center">
					<%= f.submit "Update", class: 'btn btn-success' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/patients/index.html.erb
<div class="col-md-12 no-gutter">
	<div class="role-show">
		<div class="clear"></div>
		<div class="col-md-12 no-gutter">
			<h2 class="header-title">Patients</h2>
			<div class="table-responsive">
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Account Number</th>
							<th>Patient Name</th>
							<th>Location</th>
							<th>Weight</th>
							<th>Temperature</th>
						</tr>
					</thead>
					<tbody>
						<% @users.each do |user| %>
							<% if user.account_number.present? %>
								<tr>
									<td><%= user.account_number %></td>
									<td><%= user.first_name %></td>
									<td><%= user.location.present? ? user.location : 'not mentioned' %></td>
									<td><%= user.weight.present? ? user.weight : 'not mentioned' %></td>
									<td><%= user.temperature.present? ? user.temperature : 'not mentioned' %></td>
									<td><%= link_to 'Manage Patient', manage_patient_path(user) %></td>
									<td><%= link_to 'Manage Test(s)', manage_test_path(user) %></td>
								</tr>
							<% end %>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>

app/views/patients/manage_patient.html.erb
<div class="panel-layout">
	<div class="panel panel-default">
		<div class="panel-heading">Manage Patient</div>
		<div class="panel-body">
			<%= form_for(@patient, url: update_patient_path(@patient)) do |f| %>
				<%= f.text_field :weight, placeholder: 'Enter Weight', class: 'form-control' %>
				<%= f.text_field :temperature, placeholder: 'Enter Temperature', class: 'form-control' %>
				<div class="actions text-center">
					<%= f.submit 'Update Patient', class: 'btn btn-success' %>					
				</div>
			<% end %>
			<p><strong>Weight: </strong><%= @patient.weight.present? ? @patient.weight : 'Not Mentioned' %></p>
			<p><strong>Temperature: </strong><%= @patient.temperature.present? ? @patient.temperature : 'Not Mentioned' %></p>
		</div>
	</div>
</div>

app/views/patients/manage_test.html.erb
<div class="panel-layout">
	<div class="panel panel-default">
		<div class="panel-heading">Manage Test</div>
		<div class="panel-body">
			<%= form_for(@patient_test, url: update_test_path(@patient)) do |f| %>
				<%= f.text_field :name, placeholder: 'Enter Test Name', class: 'form-control' %>
				<%= f.text_field :result, placeholder: 'Enter Test Result', class: 'form-control' %>
				<div class="btn-section text-center">
					<%= f.submit class: 'btn btn-success' %>					
				</div>
			<% end %>
		</div>
	</div>
</div>
<div class="table-responsive">
	<table class="table table-striped">
		<tr>
			<th>Test Name</th>
			<th>Test Result</th>
			<th>&nbsp;</th>
		</tr>
		<% if @patient_tests.each do |patient_test| %>
			<tr>
				<td><%= patient_test.name %></td>
				<td><%= patient_test.result %></td>
				<td><%= link_to 'Remove Test', destroy_test_path(@patient, patient_test), method: :delete %></td>
			</tr>
		<% end.blank? %>
			<tr><td>Patient didn't take any tests</td></tr>
		<% end %>
	</table>
</div>

app/views/patients/show.html.erb
<div class="table-responsive">
	<p><label>First Name</label>: <%= @patient.first_name %></p>
	<p><label>Last Name</label>: <%= @patient.last_name %></p>
	<p><label>Account Number</label>: <%= @patient.account_number %></p>
	<p><label>Location</label>: <%= @patient.location.present? ? @patient.location : 'Not mentioned' %></p>
	<p><label>Weight</label>: <%= @patient.weight.present? ? @patient.weight : 'Not mentioned' %></p>
	<p><label>Temperature</label>: <%= @patient.temperature.present? ? @patient.temperature : 'Not mentioned' %></p>
	<%= link_to 'Edit Profile', edit_profile_path, class: 'btn btn-success align-margin' %>
	<table class="table table-striped">
		<tr>
			<th>Test Name</th>
			<th>Result</th>
		</tr>
		<% if @patient.patient_tests.each do |patient_test| %>
			<tr>
				<td><%= patient_test.name %></td>
				<td><%= patient_test.result %></td>
			</tr>
		<% end.blank? %>
			<tr><td>Patient didn't take any tests</td></tr>
		<% end %>
	</table>
</div>