config/routes.rb
Rails.application.routes.draw do
  resources :hospital_profiles
  resources :patient_tests
  devise_for :users, :controllers => { registrations: 'registrations'}

  root :to => 'home#index'
  resources :roles
  get '/role/:id/abilities'     => 'roles#change_abilities',  as: :change_role_abilities
  post '/role/:id/update-abilities' => 'roles#update_abilities',  as: :update_role_abilities
  get '/patients' => 'patients#index'
  get '/manage-patient/:id' => 'patients#manage_patient', as: :manage_patient
  patch '/update-patient/:id' => 'patients#update_patient', as: :update_patient
  get '/manage-test/:id' => 'patients#manage_test', as: :manage_test
  post '/update-test/:id' => 'patients#update_test', as: :update_test
  delete '/manage-test/:id/:pid' => 'patients#destroy_test', as: :destroy_test
  get '/manage-profile/:id' => 'patients#show', as: :profile
  get '/edit-profile/:id' => 'patients#edit', as: :edit_profile
  put '/update-profile/:id' => 'patients#update_profile', as: :update_profile

end

app/models/role.rb
class Role
	include Mongoid::Document
	has_and_belongs_to_many :users, class_name: 'User'
	has_and_belongs_to_many :permissions, class_name: 'Permission'
	belongs_to :resource, :polymorphic => true

	field :name, :type => String

	index({
		:name => 1,
		:resource_type => 1,
		:resource_id => 1
	},
	{ :unique => true})

	validates :resource_type,
						:inclusion => { :in => Rolify.resource_types },
						:allow_nil => true

	scopify

	def is_permission_exist?(permission_id)
		permissions.where(_id: permission_id).count > 0 ? true : false
	end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
	
	#devise so that only logged-in user can access	
	before_filter :load_permissions
	load_and_authorize_resource
	before_action :set_role, only: [:show, :edit, :update, :destroy, :change_abilities, :update_abilities]

	def index
		@roles = Role.page(params[:page]).per(30)
	end

	def new
		@role = Role.new
	end

	def show
		@abilities = @role.permissions
	end

	def edit

	end

	def create
		@role = Role.new(role_params)
		if @role.save
			flash[:notice] = 'Role was successfully created.'
			redirect_to roles_path
		else
			render 'new'
		end
	end

	def update
		if @role.update(role_params)
			flash[:notice] = 'Role was successfully updated.'
			redirect_to role_path(@role)
		else
			render 'edit'
		end
	end

	def destroy
		@role.destroy
		redirect_to roles_path
	end

	def change_abilities
		@abilities = Permission.all
	end

	def update_abilities
		if params[:ability].present?
			@role.permissions = []
			params[:ability].each do |ability_id|
				ability = Permission.find(ability_id)
				@role.permissions << ability
			end
			redirect_to role_path(@role)
		else
			flash[:notice] = 'Please select atleast one ability'
			redirect_to change_role_abilities_path(@role)
		end
	end

	private

	def role_params
		params.require(:role).permit(:name)
	end

	def set_role
		@role = Role.find(params[:id])
	end
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
	<% if @role.errors.full_messages.any? %>
		<% @role.errors.full_messages.each do |message| %>
			<p id="notice"><%= message %></p>
		<% end %>
	<% end %>
	<%= f.text_field :name, class: 'form-control', :placeholder => 'Enter Role' %>
	<div class='actions extra-margin-top pull-right'>
		<%= f.submit 'Submit', class: 'btn btn-info' %>
	</div>
<% end %>

app/views/roles/change_abilities.html.erb
<div class="col-md-12 no-gutter">
	<div class="change-abilities">
		<%= form_tag(update_role_abilities_path(@role), method: :post) do %>
		<h2 class="header-title">Change Abilities in <%= @role.name.titleize %><span><%= submit_tag 'Update Abilities', class: 'btn btn-primary pull-right' %></span></h2>
		<div class="table-responsive">
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Model</th>
						<th>Action</th>
						<th>Ability</th>
						<th>&nbsp;</th>
					</tr>
				</thead>
				<tbody>
					<% @abilities.each do |ability| %>
						<tr>
							<td><%= ability.subject_class %></td>
							<td><%= ability.action %></td>
							<td><%= ability.name %></td>
							<td><%= check_box_tag 'ability[]', ability.id,  @role.is_permission_exist?(ability.id) %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<div class="col-md-12 no-gutter">
			<%= submit_tag 'Update Abilities', class: 'btn btn-primary pull-right' %>
		</div>
		<% end %>
	</div>
</div>

app/views/roles/edit.html.erb
<div class="role-edit">
	<div class="block-center mt-xl wd-xl">
		<div class="panel">
			<h2 class="header-title panel-title">Editing Role</h2>
			<div class="panel-body">
				<%= render 'form' %>
				<span class="pull-left extra-margin-top margin-bottom">
					<%= link_to 'Back', roles_path, class: 'btn btn-info' %>
					<%= link_to 'Show', @role, class: 'btn btn-info' %>
				</span>
			</div>
		</div>
	</div>
</div>

app/views/roles/index.html.erb
<div class="col-md-12">
	<h2 class="header-title">Listing Roles<span><%= link_to 'New Role', new_role_path, class: 'btn btn-primary pull-right' %></span></h2>
	<!-- pagination html start -->
	<div class="text-center">
		<div class="panel pagination">
			<%= paginate @roles %>
		</div>
	</div>
	<!-- pagination html end -->
	<div class="table-responsive roles-list">
		<table class='table table-striped'>
			<thead>
				<th>Role</th>
				<th colspan="2">&nbsp;</th>
			</thead>
			<tbody>
				<% @roles.each do |role| %>
					<tr>
						<td class="role-name"><%= link_to role.name.titleize, role %></td>
						<td><%= link_to 'Edit', edit_role_path(role), class: 'btn btn-info' %></td>
						<td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<!-- pagination html start -->
	<div class="text-center">
		<div class="panel pagination">
			<%= paginate @roles %>
		</div>
	</div>
	<!-- pagination html end -->
	<div class="clear"></div>
	<div class="col-md-12 no-gutter">
		<%= link_to 'New Role', new_role_path, class: 'btn btn-primary pull-right' %>
	</div>
</div>

app/views/roles/new.html.erb
<div class="role-new">
	<div class="block-center mt-xl wd-xl">
		<div class="panel">
			<h2 class="header-title panel-title">New Role</h2>
			<div class="extra-margin-top panel-body">
				<%= render 'form' %>
				<%= link_to 'Back', roles_path, class: 'btn btn-info back-btn extra-margin-top margin-bottom pull-left' %>
			</div>
		</div>
	</div>
</div>

app/views/roles/show.html.erb
<div class="col-md-12 no-gutter">
	<div class="role-show">
		<div class="col-md-4 col-md-offset-4 no-gutter">
			<div class="table-responsive role-title">
				<table class="table table-striped">
					<tbody>
						<tr>
							<td class="name-text">Role Name</td>
							<td>:</td>
							<td class="name"><strong><%= @role.name.titleize %></strong></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<div class="clear"></div>
		<div class="col-md-12 no-gutter">
			<h2 class="header-title">Abilities<span><%= link_to 'Add/Change Abilities', change_role_abilities_path(@role), class: 'btn btn-primary pull-right' %></span></h2>
			<div class="table-responsive">
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Model</th>
							<th>Action</th>
							<th>Ability</th>
						</tr>
					</thead>
					<tbody>
						<% @abilities.each do |ability| %>
							<tr>
								<td><%= ability.subject_class %></td>
								<td><%= ability.action %></td>
								<td><%= ability.name %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
		<div class="clear"></div>
		<div class="col-md-12 no-gutter extra-margin-top">
			<%= link_to 'Back', roles_path, class: 'btn btn-info' %>
			<%= link_to 'Edit', edit_role_path(@role), class: 'btn btn-info' %>
			<%= link_to 'Add/Change Abilities', change_role_abilities_path(@role), class: 'btn btn-primary pull-right' %>
		</div>
	</div>
</div>